package com.skhealth.guardian.mobile

import android.app.Activity
import android.os.Bundle
import android.widget.*
import com.skhealth.guardian.shared.AlarmConfig

class MeasurementSettingsActivity : Activity() {
 private lateinit var root:LinearLayout
 private fun number(label:String,value:Int)=UiStyle.labeledField(this,label,value.toString(),true)
 private fun input(field:LinearLayout)=UiStyle.labeledFieldInput(field)
 override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);UiStyle.applyBars(this);val cfg=AppSettings.load(this);root=UiStyle.page(this);setContentView(ScrollView(this).apply{setBackgroundColor(UiStyle.BG);addView(root)})
  root.addView(UiStyle.detailHeader(this,"Ölçüm ve alarm ayarları","Tüm eşikler telefondan yönetilir. Değişiklikler Galaxy Watch'a otomatik gönderilir."))
  val health=UiStyle.card(this);health.addView(UiStyle.text(this,"SpO₂ ve nabız",19f,UiStyle.TEXT,true))
  val spo2Critical=number("Kritik SpO₂ (%)",cfg.spo2CriticalImmediate);val spo2Low=number("Düşük SpO₂ (%)",cfg.spo2LowThreshold);val spo2Confirm=number("Düşük SpO₂ doğrulama sayısı",cfg.spo2ConfirmCount);val hrHigh=number("Yüksek nabız (bpm)",cfg.heartRateHighThreshold);val hrHighConfirm=number("Yüksek nabız doğrulama sayısı",cfg.heartRateHighConfirmCount);val hrLowEnabled=UiStyle.check(this,"Düşük nabız alarmı aktif",cfg.heartRateLowEnabled);val hrLow=number("Düşük nabız (bpm)",cfg.heartRateLowThreshold);val hrLowConfirm=number("Düşük nabız doğrulama sayısı",cfg.heartRateLowConfirmCount);listOf(spo2Critical,spo2Low,spo2Confirm,hrHigh,hrHighConfirm).forEach(health::addView);health.addView(hrLowEnabled);listOf(hrLow,hrLowConfirm).forEach(health::addView);root.addView(health)
  val watch=UiStyle.card(this);watch.addView(UiStyle.text(this,"Galaxy Watch",19f,UiStyle.TEXT,true));val stale=number("Veri gelmeme alarmı (dk)",(cfg.staleDataMs/60000L).toInt());val watchInterval=number("Normal ölçüm aralığı (dk)",AppSettings.watchMeasurementMinutes(this));val watchConfirmDelay=number("Düşük değer doğrulama gecikmesi (dk)",AppSettings.watchConfirmMinutes(this));val retry1=number("Teknik hata 1. tekrar (sn)",AppSettings.watchRetry1Seconds(this));val retry2=number("Teknik hata 2. tekrar (sn)",AppSettings.watchRetry2Seconds(this));listOf(stale,watchInterval,watchConfirmDelay,retry1,retry2).forEach(watch::addView);root.addView(watch,UiStyle.sectionParams(this))
  val pc=UiStyle.card(this);pc.addView(UiStyle.text(this,"PC-60FW",19f,UiStyle.TEXT,true));pc.addView(UiStyle.text(this,"Geçerli ve güncel veri üretirken öncelikli ölçüm kaynağıdır.",14f,UiStyle.MUTED).apply{setPadding(0,UiStyle.dp(this@MeasurementSettingsActivity,6),0,0)});val pcAlarm=number("Alarm eşiği (≤ %)",AppSettings.pc60AlarmThreshold(this));val pcConfirm=number("Düşük SpO₂ bekleme süresi (dk)",AppSettings.pc60ConfirmMinutes(this));val pcRecovery=number("Toparlanma eşiği (> %)",AppSettings.pc60RecoveryThreshold(this));val pcStable=number("Toparlanma stabilizasyonu (sn)",AppSettings.pc60StableSeconds(this));listOf(pcAlarm,pcConfirm,pcRecovery,pcStable).forEach(pc::addView);root.addView(pc,UiStyle.sectionParams(this))
  val remote=UiStyle.card(this);remote.addView(UiStyle.text(this,"Uzaktan uyarı",19f,UiStyle.TEXT,true));val escalation=number("Yanıt yoksa tekrar uyar (dk, 0=kapalı)",AppSettings.escalationMinutes(this));val escalationMaxAge=number("Reboot sonrası eski alarmı geri yükleme üst sınırı (dk)",AppSettings.escalationMaxAgeMinutes(this));remote.addView(escalation);remote.addView(escalationMaxAge);root.addView(remote,UiStyle.sectionParams(this))
  root.addView(UiStyle.button(this,"Tüm ayarları kaydet").apply{setOnClickListener{val critical=input(spo2Critical).intOr(80);val low=input(spo2Low).intOr(90);val lowCount=input(spo2Confirm).intOr(2);val high=input(hrHigh).intOr(130);val highCount=input(hrHighConfirm).intOr(2);val lowHr=input(hrLow).intOr(45);val lowHrCount=input(hrLowConfirm).intOr(2);val staleMin=input(stale).intOr(10);val escalationMin=input(escalation).intOr(0);val escalationMaxAgeMin=input(escalationMaxAge).intOr(60);val intervalMin=input(watchInterval).intOr(5);val confirmMin=input(watchConfirmDelay).intOr(2);val retry1Sec=input(retry1).intOr(30);val retry2Sec=input(retry2).intOr(60);val pcAlarmValue=input(pcAlarm).intOr(85);val pcConfirmMin=input(pcConfirm).intOr(2);val pcRecoveryValue=input(pcRecovery).intOr(85);val pcStableSec=input(pcStable).intOr(10)
   if(critical !in 50..99||low !in 51..100||critical>=low)return@setOnClickListener toast("SpO₂ eşiklerini kontrol et");if(lowCount !in 1..5||highCount !in 1..5||lowHrCount !in 1..5)return@setOnClickListener toast("Doğrulama sayıları 1–5 olmalı");if(high !in 60..240||lowHr !in 25..120||lowHr>=high)return@setOnClickListener toast("Nabız eşiklerini kontrol et");if(staleMin !in 5..120||escalationMin !in 0..60||escalationMaxAgeMin !in 5..1440)return@setOnClickListener toast("Süre ayarlarını kontrol et");if(intervalMin !in 1..60||confirmMin !in 1..10)return@setOnClickListener toast("Saat ölçüm sürelerini kontrol et");if(retry1Sec !in 5..300||retry2Sec !in 5..600||retry2Sec<retry1Sec)return@setOnClickListener toast("Teknik tekrar sürelerini kontrol et");if(pcAlarmValue !in 50..99||pcRecoveryValue !in 50..99||pcConfirmMin !in 1..10||pcStableSec !in 3..120)return@setOnClickListener toast("PC-60FW ayarlarını kontrol et")
   AppSettings.setEscalationMinutes(this@MeasurementSettingsActivity,escalationMin);AppSettings.setEscalationMaxAgeMinutes(this@MeasurementSettingsActivity,escalationMaxAgeMin);AppSettings.setWatchMeasurementMinutes(this@MeasurementSettingsActivity,intervalMin);AppSettings.setWatchConfirmMinutes(this@MeasurementSettingsActivity,confirmMin);AppSettings.setWatchRetry1Seconds(this@MeasurementSettingsActivity,retry1Sec);AppSettings.setWatchRetry2Seconds(this@MeasurementSettingsActivity,retry2Sec);AppSettings.setPc60AlarmThreshold(this@MeasurementSettingsActivity,pcAlarmValue);AppSettings.setPc60ConfirmMinutes(this@MeasurementSettingsActivity,pcConfirmMin);AppSettings.setPc60RecoveryThreshold(this@MeasurementSettingsActivity,pcRecoveryValue);AppSettings.setPc60StableSeconds(this@MeasurementSettingsActivity,pcStableSec);AppSettings.save(this@MeasurementSettingsActivity,AlarmConfig(critical,low,lowCount,high,highCount,hrLowEnabled.isChecked,lowHr,lowHrCount,staleMin*60000L));WatchStatusStore.mark(this@MeasurementSettingsActivity,"CONFIG_BEKLENİYOR | saat ACK bekleniyor");toast("Ayarlar kaydedildi; saat onayı bekleniyor")}})
 }
 private fun EditText.intOr(default:Int)=text.toString().toIntOrNull()?:default
 private fun toast(text:String)=Toast.makeText(this,text,Toast.LENGTH_LONG).show()
}
